### ISSUE TITLE
Update runtime to 3.34

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.cvfosammmm.Setzer#1]

**Comment by cvfosammmm** [comment]
That depends on https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/11 . 3.34 depends on the freedesktop 19.08 runtime, for which there is currently not texlive extension.

**Comment by jakobjakobson13** [comment]
> That depends on [flathub/org.freedesktop.Sdk.Extension.texlive#11](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/11) . 3.34 depends on the freedesktop 19.08 runtime, for which there is currently not texlive extension.

That [issue](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/11) has been [solved](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/pull/14)

**Comment by cvfosammmm** [comment]
The build fails saying "org.gnome.Sdk/x86_64/3.34 not installed" among other thing. Perhaps someone can help.

https://flathub.org/builds/#/builders/27/builds/10292

**Comment by cvfosammmm** [comment]
Done
