### ISSUE TITLE
Cannot update Setzer (404)

### ISSUE THREAD

**Issue by jvnknvlgl** [flathub/org.cvfosammmm.Setzer#13]
When I try try to update Setzer, I get the following error:

```
Error: While pulling app/org.cvfosammmm.Setzer/x86_64/stable from remote flathub: Server returned HTTP 404
Updates complete.
error: There were one or more errors
```

**Comment by cvfosammmm** [comment]
Looks like a problem with the server, can you try it again?

**Comment by jvnknvlgl** [comment]
I have tried it many times, also some minutes ago, but it still doesn't work. It stops at about 20-30MB.

**Comment by cvfosammmm** [comment]
I don't know what's going on. Maybe you can try uninstalling and installing again.

**Comment by jvnknvlgl** [comment]
Of course that fixed it, thank you very much!
